server:
  port: 8081
#debug: true

#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.cloud: DEBUG
#    org.springframework.web: WARN

security:
  oauth2:
    client:
      client-id: first-client
      client-secret: noonewilleverguess

#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp